-- MySQL Script generated by MySQL Workbench
-- Mon Apr 19 14:43:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agro` ;

-- -----------------------------------------------------
-- Schema agro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agro` DEFAULT CHARACTER SET utf8 ;
USE `agro` ;

-- -----------------------------------------------------
-- Table `agro`.`praga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agro`.`praga` ;

CREATE TABLE IF NOT EXISTS `agro`.`praga` (
  `id_praga` INT NOT NULL,
  `nome_praga` VARCHAR(45) NOT NULL,
  `inicio_praga` DATE NOT NULL,
  `termino_praga` DATE NOT NULL,
  PRIMARY KEY (`id_praga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agro`.`cultura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agro`.`cultura` ;

CREATE TABLE IF NOT EXISTS `agro`.`cultura` (
  `id_cultura` INT NOT NULL,
  `nome_cultura` VARCHAR(45) NOT NULL,
  `regiao_cultura` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cultura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agro`.`regiao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agro`.`regiao` ;

CREATE TABLE IF NOT EXISTS `agro`.`regiao` (
  `id_regiao` INT NOT NULL,
  `regiao_tipo` VARCHAR(45) NOT NULL,
  `id_praga` INT NOT NULL,
  `id_cultura` INT NOT NULL,
  PRIMARY KEY (`id_regiao`),
  INDEX `id_praga_re_idx` (`id_praga` ASC) VISIBLE,
  INDEX `id_cultura_re_idx` (`id_cultura` ASC) VISIBLE,
  CONSTRAINT `id_praga_re`
    FOREIGN KEY (`id_praga`)
    REFERENCES `agro`.`praga` (`id_praga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cultura_re`
    FOREIGN KEY (`id_cultura`)
    REFERENCES `agro`.`cultura` (`id_cultura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agro`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agro`.`usuario` ;

CREATE TABLE IF NOT EXISTS `agro`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `tipo_usuario` DECIMAL(10) NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `id_regiao` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `id_regiao_usu_idx` (`id_regiao` ASC) VISIBLE,
  CONSTRAINT `id_regiao_usu`
    FOREIGN KEY (`id_regiao`)
    REFERENCES `agro`.`regiao` (`id_regiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
