-- MySQL Script generated by MySQL Workbench
-- Wed May  5 11:24:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`praga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`praga` ;

CREATE TABLE IF NOT EXISTS `mydb`.`praga` (
  `id_praga` INT NOT NULL,
  `nome_praga` VARCHAR(45) NOT NULL,
  `inicio_praga` DATE NOT NULL,
  `termino_praga` DATE NULL,
  PRIMARY KEY (`id_praga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cultura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cultura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cultura` (
  `id_cultura` INT NOT NULL,
  `nome_cultura` VARCHAR(45) NOT NULL,
  `id_praga` INT NOT NULL,
  PRIMARY KEY (`id_cultura`),
  INDEX `id_praga_cultura_idx` (`id_praga` ASC) VISIBLE,
  CONSTRAINT `id_praga_cultura`
    FOREIGN KEY (`id_praga`)
    REFERENCES `mydb`.`praga` (`id_praga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`regiao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`regiao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`regiao` (
  `id_regiao` INT NOT NULL,
  `regiao_tipo` VARCHAR(45) NOT NULL,
  `id_cultura` INT NOT NULL,
  PRIMARY KEY (`id_regiao`),
  INDEX `id_cultura_re_idx` (`id_cultura` ASC) VISIBLE,
  CONSTRAINT `id_cultura_re`
    FOREIGN KEY (`id_cultura`)
    REFERENCES `mydb`.`cultura` (`id_cultura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `tipo_usuario` DECIMAL(10) NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `id_regiao` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `id_regiao_usu_idx` (`id_regiao` ASC) VISIBLE,
  CONSTRAINT `id_regiao_usu`
    FOREIGN KEY (`id_regiao`)
    REFERENCES `mydb`.`regiao` (`id_regiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
